src/accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import UserLoginView
from .views import UserLogoutView
from .views import UserProfileUpdateView
from .views import UserRegisterView
from .views import user_activate
from .views import user_profile_view

app_name = 'accounts'

urlpatterns = [
    path('register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('register/done/',
         TemplateView.as_view(template_name='accounts/user_register_done.html'), name='register_done'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/', user_profile_view, name='profile'),
    path('profile/update/', UserProfileUpdateView.as_view(), name='profile_update'),
]

src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/models.py
import os.path

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models


def avatar_save(instance, filename):
    f_name = f'profile/{instance.username}_logo'
    if os.path.exists(settings.MEDIA_ROOT / f_name):
        os.remove(settings.MEDIA_ROOT / f_name)
    return f_name


class User(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True)
    avatar = models.ImageField(upload_to=avatar_save, default='profile/default.png')
    birthday = models.DateField(null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)

    class Meta(AbstractUser.Meta):
        db_table = 'user'

    def __str__(self):
        return self.username

src/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserChangeForm
from django.core.exceptions import ValidationError
from django.forms import widgets

from .apps import user_register


class UserRegisterFrom(forms.ModelForm):
    email = forms.EmailField(label='email')
    password1 = forms.CharField(
        label='password',
        widget=forms.PasswordInput,
        help_text=password_validation.password_validators_help_text_html
    )
    password2 = forms.CharField(
        label='confirm password',
        widget=forms.PasswordInput,
        help_text='please repeat password'
    )

    def clean_password1(self):
        pwd = self.cleaned_data['password1']
        if pwd:
            password_validation.validate_password(pwd)
        return pwd

    def clean(self):
        super().clean()
        pwd1 = self.cleaned_data.get('password1')
        pwd2 = self.cleaned_data.get('password2')
        if pwd1 and pwd2 and pwd1 != pwd2:
            raise ValidationError(
                {
                    'password2': ValidationError('Password not equals', code='password_mismatch')
                }
            )

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_activated = False
        user.is_active = False

        if commit:
            user.save()

        user_register.send(UserRegisterFrom, instance=user)

        return user

    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'email',
            'password1',
            'password2',
        )


class UserUpdateForm(UserChangeForm):
    avatar = forms.ImageField(required=False, widget=widgets.FileInput())
    birthday = forms.DateField(required=False, widget=widgets.DateInput(attrs={'type': 'date'}))
    email = forms.EmailField(required=True)

    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'birthday',
            'city',
            'avatar'
        )

        # widgets = {'birthday': forms.DateInput(attrs={'type': 'date'})}


class UserRetryVerification(forms.Form):
    email = forms.EmailField()

src/accounts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.core.signing import BadSignature
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import UpdateView

from .forms import UserRegisterFrom, UserUpdateForm, UserRetryVerification
from .utils import signer, send_activation_notification


class UserRegisterView(CreateView):
    model = get_user_model()
    template_name = 'accounts/user_register.html'
    success_url = reverse_lazy('accounts:register_done')
    form_class = UserRegisterFrom


def user_activate(request, sign):
    if request.method == 'POST':
        form = UserRetryVerification(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            try:
                user = get_user_model().objects.get(email__iexact=email)
            except get_user_model().DoesNotExist:
                return redirect('accounts:register')

            if user.is_activated:
                return redirect('password_reset')

            send_activation_notification(user)
            return redirect('accounts:register_done')
    else:
        form = UserRetryVerification()
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'accounts/bad_signature.html', {'form': form})

    user = get_object_or_404(get_user_model(), username=username)
    if user.is_activated:
        template = 'accounts/user_is_activated.html'
    else:
        template = 'accounts/user_activation_done.html'
        user.is_activated = True
        user.is_active = True
        user.save()

    return render(request, template)


class UserLoginView(LoginView):
    template_name = 'accounts/user_login.html'


class UserLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'accounts/user_logout.html'


@login_required
def user_profile_view(request):
    return render(request, 'accounts/user_profile.html')


class UserProfileUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'accounts/user_profile_update.html'
    model = get_user_model()
    success_url = reverse_lazy('accounts:profile')
    form_class = UserUpdateForm

    def get_object(self, queryset=None):
        return self.request.user

src/accounts/templates/accounts/bad_signature.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}
    Activation failed
{% endblock %}

{% block header %}
    Activation failed.
{% endblock %}

{% block content %}
   <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                <p>Wrong verification link. Write your email, so we can send to you verification link.</p>
                {% csrf_token %}
                {{ form|crispy }}
                <div class="mt-3 text-center">
                    <input class="btn btn-outline-primary" type="submit" value="Send">
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

src/accounts/templates/accounts/user_activation_done.html
{% extends 'base.html' %}

{% block title %}
    Activation completed
{% endblock %}

{% block header %}
    Activation completed.
{% endblock %}

{% block content %}
    <p>You have successfully activated your account.</p>
    <p><a href="{% url 'accounts:login' %}">Please login.</a></p>
{% endblock %}

src/accounts/templates/accounts/user_is_activated.html
{% extends 'base.html' %}

{% block title %}
    User already activated
{% endblock %}

{% block header %}
    User already activated.
{% endblock %}

{% block content %}
    <p>You have previously activated your account.</p>
    <p><a href="{% url 'accounts:login' %}">Please login.</a></p>
{% endblock %}

src/accounts/templates/accounts/user_login.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}
    Login
{% endblock %}

{% block header %}
    Login page
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                {{ form | crispy }}
                    <a href="{% url 'password_reset' %}">If you forgot your password, click me!</a>
                <div class="mt-3 text-center">
                    <input class="btn btn-outline-primary" type="submit" value="Login">
                    <a href="{% url 'accounts:register' %}" class="btn btn-outline-success">Register</a>
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

src/accounts/templates/accounts/user_logout.html
{% extends 'base.html' %}

{% block title %}
    Logout user
{% endblock %}

{% block header %}
    You have successfully logged out of the site.
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col text-center">
            <a href="{% url 'index' %}" class="btn btn-outline-success">Home</a>
            <a href="{% url 'accounts:login' %}" class="btn btn-outline-success">Login</a>
            <a href="{% url 'accounts:register' %}" class="btn btn-outline-success">Register</a>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

src/accounts/templates/accounts/user_profile.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    User profile
{% endblock %}

{% block header %}
    {{ user.username }} profile.
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-2"></div>
        <div class="col">
            <div class="row">
                <div class="col-6 text-center">
                    <img class="rounded-circle p-1 m-1" width="200" height="200" src="{{ user.avatar.url }}"
                         alt="avatar">
                </div>
                <div class="col-6">
                    <div class="row">
                        <label for="username" class="col-4"><strong>Username:</strong></label>
                        <div class="col-8">
                            <p id="username">{{ user.username }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <label for="email" class="col-4"><strong>E-Mail:</strong></label>
                        <div class="col-8">
                            <p id="email">{{ user.email }}</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-6">
                    <label for="firstname" class="col-4"><strong>First name:</strong></label>
                    <div class="col-8">
                        <p id="firstname">{{ user.first_name }}</p>
                    </div>
                </div>
                <div class="col-6">
                    <label for="lastname" class="col-4"><strong>Last name:</strong></label>
                    <div class="col-8">
                        <p id="lastname">{{ user.last_name }}</p>
                    </div>
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-6">
                    <label for="birthday" class="col-4"><strong>Birthday:</strong></label>
                    <div class="col-8">
                        <p id="birthday">{% if user.birthday %}{{ user.birthday }}{% endif %}</p>
                    </div>
                </div>
                <div class="col-6">
                    <label for="city" class="col-4"><strong>City:</strong></label>
                    <div class="col-8">
                        <p id="city">{% if user.city %}{{ user.city }}{% endif %}</p>
                    </div>
                </div>
            </div>
            <div class="row mt-4 text-center">
                <div class="col">
                    <a class="btn btn-outline-primary" href="{% url 'accounts:profile_update' %}">Change profile</a>
                    <a class="btn btn-outline-primary" href="{% url 'password_change' %}">Change password</a>
                </div>
            </div>
        </div>
        <div class="col-2"></div>
    </div>

{% endblock %}

src/accounts/templates/accounts/user_profile_update.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}
{% load crispy_forms_field %}

{% block title %}
    Update profile
{% endblock %}

{% block header %}
    Update your profile
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-2"></div>
            <div class="col">
                <div class="row">
                    <div class="col-6 text-center">
                        <div class="media">
                            <div class="img-circle.vert">
                                <img class="rounded-circle p-1 m-1" width="100" height="100" src="{{ user.avatar.url }}"
                                     alt="avatar">
                            </div>
                            <div class="media-body p-3 m-3">
                                <h2 class="account-heading">{{ user.username }}</h2>
                                <h3 class="account-heading">{{ user.first_name }} {{ user.last_name }}</h3>
                                <p class="text-secondary">{{ user.email }}</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        {{ form.username|as_crispy_field }}
                        {{ form.email|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        {{ form.first_name|as_crispy_field }}
                    </div>
                    <div class="col-6">
                        {{ form.last_name|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        {{ form.birthday|as_crispy_field }}
                    </div>
                    <div class="col-6">
                        {{ form.city|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        {{ form.avatar|as_crispy_field }}
                    </div>
                </div>
                <div class="mt-3 mb-3 text-center">
                    <input class="btn btn-outline-success mt-3" type="submit" value="Update">
                    <a class="btn btn-outline-success mt-3" href="{% url 'accounts:profile' %}">Cancel</a>
                </div>
            </div>
            <div class="col-2"></div>
        </div>

    </form>
    <script>
{% endblock %}

src/accounts/templates/accounts/user_register.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}
    Create account
{% endblock %}

{% block header %}
    Registration new user
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="mt-3 text-center">
                    <input class="btn btn-outline-primary" type="submit" value="Register">
                    <a href="{% url 'accounts:login' %}" class="btn btn-outline-success">Login</a>
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

src/accounts/templates/accounts/user_register_done.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Registration completed
{% endblock %}

{% block header %}
    Registration completed.
{% endblock %}

{% block content %}
    <p>User registration completed.</p>
    <p>An email has been sent to your email address to activate your account.</p>
    <div class="mt-3 text-center">
        <a href="{% url 'index' %}" class="btn btn-outline-success">To Home</a>
    </div>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>QUIZ - {% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
    <body>
        {% include 'includes/header.html' %}
        <div class="container mt-4 pt-5">
            <div class="border rounded text-center p-3 m-3 mb-5 bg-light shadow">
                <h1>{% block header %}{% endblock %}</h1>
            </div>
            {% block content %}{% endblock %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
                crossorigin="anonymous"></script>
    </body>
</html>

src/templates/includes/header.html
{% load static %}

<nav class="navbar navbar-expand-lg mb-2 fixed-top" style="background-color: #e3f2fd;">
    <div class="container">
{#        <a class="navbar-brand" href="#">#}
{#            <img src="{% static 'img/logo.png' %}" alt="LMS" width="30" height="24">#}
{#        </a>#}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Exam list</a>
                </li>
            </ul>
            {% if request.path %}

            {% endif %}
            {#      <form class="d-flex" role="search">#}
            {#        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">#}
            {#        <button class="btn btn-outline-success" type="submit">Search</button>#}
            {#      </form>#}
            <div class="d-flex">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">User
                        </a>
                        <ul class="dropdown-menu">
                            {% if user.is_authenticated %}
                                <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">Profile</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'password_change' %}">Change password</a></li>
                                <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a></li>
                                <li><a class="dropdown-item" href="{% url 'accounts:register' %}">Register</a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

src/templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block header %}Welcome to Quiz!!!{% endblock %}